### ISSUE TITLE
Benisty2024 Conversion (HigleyLab)

### ISSUE THREAD

**Issue by alessandratrapani** [catalystneuro/higley-lab-to-nwb#16]
This is to organize the conversion. 
Some general resources.

1. [analysis code](https://github.com/cardin-higley-lab/Benisty_Higley_2023)
2.  [Dual color mesoscopic imaging reveals spatiotemporally heterogeneous coordination of cholinergic and neocortical activity](https://www.nature.com/articles/s41593-023-01498-y)

TO-DO:

- [x] Add conversion notes
- [x] Add raw meso imaging interface (ScanImage) (#2)
- [x] Time alignment for meso imaging streams (#12)
- [ ] Add 2p imaging interface
- [ ] Add 2p+meso imaging interface
- [x] Add TTL synch signals (.smrx) (#4, #6, #8)
- [ ] Add segmentation manual
- [ ] Add segmentation suite2p 
- [x] Add raw behavior interface (.avi) (#3, #9)
- [x] Add wheel motion  (.smrx) (#5)
- [x] Add processed behavior interface for [FaceMap](https://github.com/MouseLand/facemap) output (.mat) (#11)
- [ ] Add visual stimuli interface (.csv)
- [ ] Add session and subject metadata
- [ ] Run a stub conversion for the data we have and use the inspector. 
- [ ] Run stubs
- [ ] Run validation using inspector
- [ ] Run full conversion
- [ ] Run validation.
- [ ] Create demos notebook 
- [ ] Upload the dandi
- [ ] Set the requirements.
- [ ] Modify the documentation in the readme.
